### ISSUE TITLE
FullScreen option?

### ISSUE THREAD

**Issue by d3nni** [braycarlson/alphares#1]
Hello and thanks for you nice tool, but would it be possible that ther will be a FullScreen function added? To bad I have no C++ skill to do it myself.

- Example:

FullScreen   [ X ]

Change lines...

LastConfirmedFullscreenMode=1
PreferredFullscreenMode=1

to...

LastConfirmedFullscreenMode=0
PreferredFullscreenMode=0

and add...

FullscreenMode=0

 in "GameUserSettings.ini"

Thanks a lot!! :)

**Comment by braycarlson** [comment]
Hi @d3nni. Thank-you for your suggestion. A fullscreen and FPS setting have been added to alphares v1.1. You can download it [here](https://github.com/braycarlson/alphares/releases).

**Comment by d3nni** [comment]
Thanks a lot for your work... It's working great.

Now my question would be, if it's not that hard if I could add some other custom configurations?!

I can give you some examples....

- Settings Changer

Show Grass = True / False
Show FPS = True / False
Disable Mouse Acceleration = True / False
Use VSync = True / False
Motion Blur = True / False


- ScabilityGroups

( 0 = Low or Off / 1 = Medium / 2 = High / 3 = Epic )

ResolutionQuality = X %
ViewDistanceQuality = 0 / 1 / 2 / 3
AntiAliasingQuality = 0 / 1 / 2 / 3
ShadowQuality = 0 / 1 / 2 / 3
PostProcessQuality = 0 / 1 / 2 / 3
TextureQuality = 0 / 1 / 2 / 3
EffectsQuality = 0 / 1 / 2 / 3
FoliageQuality = 0 / 1 / 2 / 3


- Advanced ScabilityGroups

( 0 = Low or Off / 1 = Medium / 2 = High / 3 = Epic )

TrueSkyQuality = 0 / 1 / 2 / 3
GroundClutterQuality = 0 / 1 / 2 / 3
IBLQuality = 0 / 1 / 2 / 3
HeightFieldShadowQuality = 0 / 1 / 2 / 3

I hope u like those ideas...  Thanks for ur time !!! :-)
