### ISSUE TITLE
help

### ISSUE THREAD

**Issue by whysatisfy** [braycarlson/alphares#10]
everytime i launch fornite and i go to fullscreen my it only shows half of the screen and its streched. I deleted alphares and i changed it back to normal resolution but that still didnt work. i tried doing windows +  R  etc, but that didnt work either. i dont know what to do and i feel like my fortnite is so different without playing full screen.

**Comment by braycarlson** [comment]
I am going to close this issue, because I have created a FAQ to address some of these common issues. You can read it here: https://github.com/braycarlson/alphares#faq. If you are still experiencing issues after reading the FAQ, then feel free to create a new issue.
