### ISSUE TITLE
Wont Start

### ISSUE THREAD

**Issue by goulzyy** [braycarlson/alphares#12]
when i tried to open alpha res it said "the code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this issue.", but when i reinstall  it gives me the same error with differenterror code numbers. How can i get it back working???

**Comment by DVRK556** [comment]
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170  

if u download this it will work

**Comment by Ahmadkh69** [comment]
bro what should we download? visual studio? i have it still alpha resolution not opening and its giving the same error again and again "the code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this issue."

**Comment by braycarlson** [comment]
From the Epic Games' [website](https://www.epicgames.com/help/en-US/epic-games-store-c5719341124379/launcher-support-c5719357217435/how-do-i-fix-the-msvcp140-dll-is-missing-windows-error-a5720244878235)

> If you received this error message you may need to reinstall the Microsoft Visual C++ Redistributables on your PC. You can locate and download this file [here](https://www.microsoft.com/en-gb/download/details.aspx?id=48145). After this completes installing restart your PC.
> 
> If you continue to have this error we recommend you reach out to [Microsoft Support](https://support.microsoft.com/en-us) as they’ll be able to help you out.

1. Go to: https://www.microsoft.com/en-gb/download/details.aspx?id=48145.
2. Press "Download".
3. Select the x86 or x64 option, depending on the architecture of your PC. If you're not sure what architecture you have, then go [here](https://support.microsoft.com/en-us/windows/32-bit-and-64-bit-windows-frequently-asked-questions-c6ca9541-8dce-4d48-0415-94a3faa2e13d).
4. Install "vc_redist.x86.exe" or "vc_redist.x64.exe".
5. Restart your PC.
6. Open alphares.
