### ISSUE TITLE
Wont open says the code execution cannot proceed

### ISSUE THREAD

**Issue by Tariktubby** [braycarlson/alphares#14]
When i try to open it it says The code execution cannot
proceed because libgcc_s_seh-1.dll was not found

**Comment by Tariktubby** [comment]
anyone know how to fix?
pls help

**Comment by babagirljuicy** [comment]
i have the same problem idk how

**Comment by braycarlson** [comment]
Hi @Tariktubby and @babagirljuicy,

I have released a new version, which should hopefully fix this issue. Please delete the old .exe and download the new release from here: https://github.com/braycarlson/alphares/releases/tag/1.2.3. Let me know if it works.

Thanks!

**Comment by Tariktubby** [comment]
It works tysm
