### ISSUE TITLE
No configuration file

### ISSUE THREAD

**Issue by vzsekalot** [braycarlson/alphares#20]
when i press apply it says "cant find this configuration file"

**Comment by braycarlson** [comment]
1. Have you opened Fortnite before using alphares?
2. Do you have a file called "GameUserSettings.ini" in "C:\Users\Brayden\AppData\Local\FortniteGame\Saved\Config\WindowsClient"?

**Comment by braycarlson** [comment]
I am going to close this issue due to inactivity and because I have created a FAQ to address some of these common issues. You can read it here: https://github.com/braycarlson/alphares#faq. If you are still experiencing issues after reading the FAQ, then feel free to create a new issue.
