### ISSUE TITLE
Clicking on Releases isnt bringing me to File

### ISSUE THREAD

**Issue by PunchMadeLo** [braycarlson/alphares#21]
It wont let me download, pops up a error page and says "Error 404 Page Not Found"

**Comment by braycarlson** [comment]
I forgot to update the README. I'll update that right now. Thank you. Does it work if you go [here](https://github.com/braycarlson/alphares/releases/tag/1.0)?

**Comment by PunchMadeLo** [comment]
Yes! Thank you
