### ISSUE TITLE
Cant run

### ISSUE THREAD

**Issue by adxhir** [braycarlson/alphares#22]
every time I try to open it says  'Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk' . what should I do

**Comment by braycarlson** [comment]
Windows SmartScreen will state that: "Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk". However, if you press "More Info", then you will be able to run the program by pressing "Run anyway". You should just have to do it once, and then it'll stop informing you of that.
