### ISSUE TITLE
doesn't change res

### ISSUE THREAD

**Issue by GeneralShepherd** [braycarlson/alphares#23]
No matter what I try I can not get it to change the games resolution, even after trying a bunch of things with nvidia too.

**Comment by braycarlson** [comment]
Have you tried a more extreme resolution such as 1080x1080? I don't know about previous patches, but on the current version of Fortnite, the in-game settings will always say 1920x1080, but my game is stretched.

One user reported success by doing the following:
1. Close Fortnite.
2. Delete the settings file (which is located: `C:/Users/Username/AppData/Local/FortniteGame/Saved/Config/WindowsClient/GameUserSettings.ini` but just remember to change "Username" to be your user account)
3. Open Fortnite (to generate a new settings file).
4. Close Fortnite.
5. Use alphares to apply a stretched resolution.
6. Open Fortnite.

**Comment by 9Bratz9** [comment]
didnt work for me my display always gets black on the frames outside

**Comment by braycarlson** [comment]
I am going to close this issue due to inactivity and because I have created a FAQ to address some of these common issues. You can read it here: https://github.com/braycarlson/alphares#faq. If you are still experiencing issues after reading the FAQ, then feel free to create a new issue.
