### ISSUE TITLE
Cant use the lower half of the screen

### ISSUE THREAD

**Issue by RealFlixz** [braycarlson/alphares#26]
When i change to a custom resalution i cant use the lowe half of the screen i cant ready up or go to the settings

**Comment by braycarlson** [comment]
I am going to close this issue due to inactivity and because I have created a FAQ to address some of these common issues. You can read it here: https://github.com/braycarlson/alphares#faq. If you are still experiencing issues after reading the FAQ, then feel free to create a new issue.
