### ISSUE TITLE
not changing res

### ISSUE THREAD

**Issue by SrirachaToes** [braycarlson/alphares#27]
it might just be me but alphares just doesnt work anymore. doesnt change the res and sometimes i get an error message from fortnite.

this only happened since new season on fn

**Comment by braycarlson** [comment]
I am going to close this issue, because I have created a FAQ to address some of these common issues. You can read it here: https://github.com/braycarlson/alphares#faq. If you are still experiencing issues after reading the FAQ, then feel free to create a new issue.
