### ISSUE TITLE
resolution going back to the normal one 

### ISSUE THREAD

**Issue by gyyatttt** [braycarlson/alphares#29]
so I was playing Fortnite and my resolution kept going back to the normal one i don't know if I'm the only one who has this issue...

**Comment by LZmiu** [comment]
i have that problem too, i click apply res and then its normal

**Comment by IsaiahGomez** [comment]
me too

**Comment by braycarlson** [comment]
Please read the FAQ: [Why is alphares not changing Fortnite's resolution?](https://github.com/braycarlson/alphares?tab=readme-ov-file#why-is-alphares-not-changing-fortnites-resolution)
