### ISSUE TITLE
Game is still stretched after Program is deleted 

### ISSUE THREAD

**Issue by semi098** [braycarlson/alphares#31]
I got The Program, But I no longer want it. I deleted it but my game is still stretched, How do I fix this?

**Comment by laami2** [comment]
did yi uget a answer i hav the same problem but my game was never strteched

**Comment by Pachachini** [comment]
press windows + r type in %localappdata% go to the FortniteGame folder then head over to the saved folder and after that goto config after that u will see the folder "WindowsClient" rightclick on it and disable Read-Only then go into the folder and disable read-only on the file called "GameUserSettings.ini"

**Comment by stocazzp** [comment]
porca di quella madonna come si toglie sta merda

**Comment by braycarlson** [comment]
Please read the FAQ: [How do I uninstall alphares?](https://github.com/braycarlson/alphares?tab=readme-ov-file#how-do-i-uninstall-alphares)
