### ISSUE TITLE
Controller not really working

### ISSUE THREAD

**Issue by mrh0und** [braycarlson/alphares#34]
Hey, with alphares i kinda have a problem when i have my controller connected, simply the x button (ps4) doesnt work in specific places for example the inventory & when im trying to leave a match its like the x dissapears & i need to use my mouse to be able to leave the match (i mean the leaving button on the friendlist, not the in-game one). I would appreciate if this got fixed asap, for the time im using ar its pretty good, nun bad to say besides this.

**Comment by braycarlson** [comment]
Please read the FAQ: [I can't do xyz in Fortnite after changing my resolution. Why?](https://github.com/braycarlson/alphares?tab=readme-ov-file#i-cant-do-xyz-in-fortnite-after-changing-my-resolution-why)
