### ISSUE TITLE
Alt+Tab makes my screen cut off

### ISSUE THREAD

**Issue by skriptkiddielmaoxd** [braycarlson/alphares#35]
whenever i tab out it cuts out a bit of the game, any ideas?

**Comment by ivoxprojects** [comment]
That's because you are using a lower res than your native res

**Comment by braycarlson** [comment]
Please read the FAQ: [I can't do xyz in Fortnite after changing my resolution. Why?](https://github.com/braycarlson/alphares?tab=readme-ov-file#i-cant-do-xyz-in-fortnite-after-changing-my-resolution-why)
