### ISSUE TITLE
fortnite in game settings

### ISSUE THREAD

**Issue by ryhliepleaseletmetap** [braycarlson/alphares#36]
when i try to change my ingame settings when i close fortnite and re open it they go back to my old settings

**Comment by tyson12578668** [comment]
when i try to change my ingame settings when i close fortnite and re open it they go back to my old settings

**Comment by fwkyid** [comment]
what worked for me was i had opened up alphares and then unchecked read only on the software itself, instead of the game files

**Comment by braycarlson** [comment]
Please read the FAQ: [Why is alphares not changing Fortnite's resolution?](https://github.com/braycarlson/alphares?tab=readme-ov-file#why-is-alphares-not-changing-fortnites-resolution)
