### ISSUE TITLE
it doesn't work in ch5 s2 

### ISSUE THREAD

**Issue by PressS04** [braycarlson/alphares#38]
it doesn't work in ch5 s2 or there is  a problem in my pc it shows that is changed  in GameUserSettings but the game dosen't change

**Comment by braycarlson** [comment]
Please read the FAQ: [Why is alphares not changing Fortnite's resolution?](https://github.com/braycarlson/alphares?tab=readme-ov-file#why-is-alphares-not-changing-fortnites-resolution)
