### ISSUE TITLE
Cant interact with anything after changing my resolution  

### ISSUE THREAD

**Issue by Zakwizardkid** [braycarlson/alphares#39]
Whenever i change the resoultion i can never be able to interact with anything and there is literally no tutorials for this i've searched it up everywhere

**Comment by braycarlson** [comment]
Please read the FAQ: [I can't do xyz in Fortnite after changing my resolution. Why?](https://github.com/braycarlson/alphares?tab=readme-ov-file#i-cant-do-xyz-in-fortnite-after-changing-my-resolution-why)
