### ISSUE TITLE
The sides get cut off when i press windows

### ISSUE THREAD

**Issue by zeiloflix** [braycarlson/alphares#41]
when i press windows it cuts off the sides a bit and it works sometimes but other times it doesn't. any ideas?

**Comment by braycarlson** [comment]
Please read the FAQ: [I can't do xyz in Fortnite after changing my resolution. Why?](https://github.com/braycarlson/alphares?tab=readme-ov-file#i-cant-do-xyz-in-fortnite-after-changing-my-resolution-why)
