### ISSUE TITLE
my strech res doesn't work on ch5 s3

### ISSUE THREAD

**Issue by JackyCh89** [braycarlson/alphares#42]
Hi, I have a standard resolution of 1920x1080, and the stretch I would like is 1440x1080. The problem is that when you start the game a part of the screen cuts off and becomes completely black, to be precise on the right, from top to bottom
![WhatsApp Image 2024-05-25 at 14 00 41](https://github.com/braycarlson/alphares/assets/170805327/58084ecb-4c5c-492e-9063-702f13f3c075)

**Comment by JackyCh89** [comment]
if anyone can resolve this problem, i litteraly can't play from the day 1 of the new season

**Comment by braycarlson** [comment]
Please read the FAQ: [I can't do xyz in Fortnite after changing my resolution. Why?](https://github.com/braycarlson/alphares?tab=readme-ov-file#i-cant-do-xyz-in-fortnite-after-changing-my-resolution-why)
