### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by s0Lzz** [braycarlson/alphares#7]
Okay so im using alpha res for fornite and I don't want it anymore so I deleted it, but the thing is it is still connected to my fortnite. Now the new season is out and Im having major issues, here are some of them. 
1. EVERY SINGLE TIME I open fornite the trailer pops up which is so darn annoying and It didnt do that before alphares
2. I wan't to switch from preformence mode do district 11 but everytime I restart fornite it goes back to what it was before which was preformence mode and the damn trailer.
Can someone please for the love of god help me, im on my last damn nerve.

**Comment by braycarlson** [comment]
alphares doesn't "connect" to Fortnite. All it does is change the following [settings](https://github.com/braycarlson/alphares/blob/master/alphares/src/alphares.cpp#L121) in a file, so you don't have to do it manually.

I suspect the "Read-only" flag is set on the settings file (which is an option when using alphares, so Fortnite does not overwrite the custom settings). So, it is possible that whenever you attempt to change your settings, then it is not properly updating.

If you're on Windows: 
- Close Fortnite.
- Press: <kbd>Win</kbd> + <kbd>R</kbd> to open a "Run" window. 
- In the box, type: `%localappdata%` and press <kbd>Enter</kbd>. 
- From there, you will have to navigate to: "FortniteGame/Saved/Config/WindowsClient/GameUserSettings.ini". 
- Right-click on "GameUserSettings.ini", then select "Properties". 
- A dialog box will open where you can check/uncheck the "Read-only" flag, and then press "Apply".

If that doesn't work, then close Fortnite and delete "GameUserSettings.ini". However, you will lose all your settings and have to set them again. Fortnite should re-generate the file when you launch the game.
