### ISSUE TITLE
big problem

### ISSUE THREAD

**Issue by Z3R010101** [braycarlson/alphares#8]
My Fortnite is totally broken. I tried uninstalling the program as all it did was pixelate my screen. After that I tried to revert my settings in the "GameUserSettings.ini" which didn't work and it made my game freeze for a good 2 minutes and crash. I then deleted "GameUserSettings.ini" so the epic games store could fix it for me. Now the trailer for the season wont even load neither can I skip it and I cant play fortnite on this pc ever again. :(

**Comment by ilikebaconeggncheese** [comment]
ima bit late but try uninstalling and reinstalling fortnite

**Comment by braycarlson** [comment]
I am going to close this issue, because I have created a FAQ to address some of these common issues. You can read it here: https://github.com/braycarlson/alphares#faq. If you are still experiencing issues after reading the FAQ, then feel free to create a new issue.
